/**
 * Specific Java classes generated by JAXB from MusicXml Opus schema.
 */
@XmlSchema(
        xmlns = {
            @XmlNs(namespaceURI = "http://www.w3.org/1999/xlink", prefix = "xlink")
        }
)
package org.audiveris.proxymusic.opus;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
