/**
 * All Java classes generated by JAXB from MusicXML schema.
 */

//@XmlSchema(
//        xmlns = {
//            @XmlNs(namespaceURI = "http://www.w3.org/1999/xlink", prefix = "xlink")
//        }
//)

//@XmlJavaTypeAdapters({
//    @XmlJavaTypeAdapter(value = MeasureAdapter.class, type = Measure.class)
//})
package org.audiveris.proxymusic;
//
//import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
//import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters;
//
//import javax.xml.bind.annotation.XmlNs;
//import javax.xml.bind.annotation.XmlSchema;
//
//import org.audiveris.proxymusic.util.MeasureAdapter;
//import org.audiveris.proxymusic.ScorePartwise.Part.Measure;
