//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 10:52:55 PM CET 
//


package proxymusic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The group-barline type indicates if the group should have common barlines. 
 * 
 * <p>Java class for group-barline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="group-barline">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>group-barline-value">
 *       &lt;attGroup ref="{}color"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "group-barline", propOrder = {
    "value"
})
public class GroupBarline {

    @XmlValue
    protected GroupBarlineValue value;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String color;

    /**
     * The group-barline-value type indicates if the group should have common barlines. Values can be yes, no, or Mensurstrich.
     * 
     * @return
     *     possible object is
     *     {@link GroupBarlineValue }
     *     
     */
    public GroupBarlineValue getValue() {
        return value;
    }

    /**
     * The group-barline-value type indicates if the group should have common barlines. Values can be yes, no, or Mensurstrich.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupBarlineValue }
     *     
     */
    public void setValue(GroupBarlineValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setColor(java.lang.String value) {
        this.color = value;
    }

}
